spring.application.name=demo

server.port = 8083

spring.datasource.url=jdbc:postgresql://localhost:5432/serviceSite
spring.datasource.username=postgres
spring.datasource.password=Estrela03
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

projeto.jwtSecrete=bxOksa8BHgdAhR80Y3pEYvS5M+MnF2sheFDqprkTqQ4odqoszJLW1ikw64/nT/dTvlgrcBTq7HfK1B9Gai2h5A==
projeto.jwtExpirationMs=900000